name: media_info_example
description: Demonstrates how to use the media_info plugin.
publish_to: 'none'

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  file_picker: ^1.4.3+2
  path_provider: ^1.5.1
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  e2e: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  media_info:
    path: ../

flutter:
  uses-material-design: true
