name: media_info
description: Determine multimedia file properties like width, height, duration
version: 0.6.0
homepage: https://github.com/ened/flutter_plugin_media_info

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  file_picker: ^1.4.3+2
  path_provider: ^1.5.1
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  e2e: ^0.2.3

flutter:
  plugin:
    platforms:
      android:
        package: asia.ivity.mediainfo
        pluginClass: MediaInfoPlugin
      ios:
        pluginClass: IVMediaInfoPlugin
